### ISSUE TITLE
remote tree walking for matching group attributes?

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#112]
4.  compare on group for remote endpoint.  Should this do the remote
lookup or can it just be ignored for attribute comparison

I am not quite sure what you mean by attribute comparison.
When it is about registration attributes, no remote lookup seems necessary
to me.

If I do the lookup of
/rd/gp-lookup?rt=foobar

And one of the groups has the following

/rd-group/xxx
https://otherrd/rd-group/yyy

I would follow the local group definition to find out if the resource type
is defined on some resource in the group, however the question is do I need
to go and query the other group which is not local in order to do the same
tree walking when doing attribute comparisons.  Not that this applies to
remote endpoint registrations in a group as well.

Thanks for the example.
Indeed following the latest text, the comparison should include the remote registration.

The text could include words like tree walking is done locally only; personally I would not be too happy about that.
Apparently the text should say something about remote groups and tree walking. I will add the issue to github.

**Comment by chrysn** [comment]
Let's not go into specifying distributed RDs but just keep the door open to not have clients break when one is even though it behaves like a regular RD (see longer comment at <https://mailarchive.ietf.org/arch/msg/core/jek5vApeH1gbb_u4JsgUkb7bD80>).

Concrete proposal from there:

Would it help if we changed the example to say                                                                                                                 
                                                                                                                                                               
    GET coap://rd.example.com/ep?gp=lights1                                                                                                                        
    Res: 2.05 Content                                                                                                                                              
    <coap+tcp://rd.example.com/rd/abcd>;con="coap://[2001:db8:3::123]:61616";                                                                                      
    ep="node1";et="oic.d.sensor";ct="40";lt="600",                                                                                                                 
    </rd/efgh>;con="coap://[2001:db8:3::124]:61616";                                                                                                               
    ep="node2";et="oic.d.sensor";ct="40";lt="600"                                                                                                                  
                                                                                                                                                               
? It would just indicate that the registration resource is hosted by the                                                                                       
same RD but on another protocol (presumably because the endpoint                                                                                               
registered using coap+tcp, and that Location can't just jump protocols).

**Comment by chrysn** [comment]
The semantics of having a foreign URI in the endpoint lookup or group are now completely left to further specification since #142 / 20cf0880957eade1d8fee1c4cf0afcb3c2683849.
