### ISSUE TITLE
registration location is not returned

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#158]
In simple registration, the location is not returned to the registrant ep.
Suggestion to return location as answer to request to RD for copying contents from /.well-known/core

**Comment by chrysn** [comment]
AFAIR this is by design to keep things simple and compact -- if one
wants a location to do full registration updates, they can do the full
registration.

What'd be the use case for returning a location?

**Comment by petervanderstok** [comment]
Same use case as for standard registration; for example: delete the
registration;
For the moment the knowledge about the location is known nowhere.
chrysn schreef op 2018-09-04 09:39:

> AFAIR this is by design to keep things simple and compact -- if one
> wants a location to do full registration updates, they can do the full
> registration.
> 
> What'd be the use case for returning a location? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/158#issuecomment-418271394
[2]

**Comment by chrysn** [comment]
I think that the idea was that simple registrations would only ever time
out, deliberately keeping it simple.

We'd have to think through whether we could return a registration at
that time at all (What would querying it give while the registration is
only half-done, ie. location was returned byt .wk/c not queried yet?
Could it be PATCHed or otherwise modified?), but the main question is
which features can be useful to devices so constrained they can't even
go through the regular registration process.

(My use case example for simple registration, back when abandoning it
was discussed, were devices that regularly NON POST to their RD server,
and the only state they keep about it is to watchdog-reboot their
network parts if no NON 2.xx comes along on the dedicated token for too
long. Had those devices been able to keep track of a location, then
they'd have done full registration right away.)

**Comment by petervanderstok** [comment]
The remark about the location was triggered by writing the interop spec.
Suppose you want to add the simple registration ep to a group?

The next realization was that no-one knows the location of the
registered ep.

The management interface also assumes that the registration location is
known.......
So, you can't add endpoints of simple registrations to a group

Any better ideas how to handle this, apart from saying that this is
typically a case for the CT?

Peter
chrysn schreef op 2018-09-04 10:07:

> I think that the idea was that simple registrations would only ever time
> out, deliberately keeping it simple.
> 
> We'd have to think through whether we could return a registration at
> that time at all (What would querying it give while the registration is
> only half-done, ie. location was returned byt .wk/c not queried yet?
> Could it be PATCHed or otherwise modified?), but the main question is
> which features can be useful to devices so constrained they can't even
> go through the regular registration process.
> 
> (My use case example for simple registration, back when abandoning it
> was discussed, were devices that regularly NON POST to their RD server,
> and the only state they keep about it is to watchdog-reboot their
> network parts if no NON 2.xx comes along on the dedicated token for too
> long. Had those devices been able to keep track of a location, then
> they'd have done full registration right away.) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/158#issuecomment-418278734
[2]

**Comment by petervanderstok** [comment]
the group concept has changed, so the issue has gone.
