### ISSUE TITLE
What does "res" do as a lookup parameter?

### ISSUE THREAD

**Issue by mjkoster** [core-wg/resource-directory#16]
We are not clear on how to use "res"in a lookup query.

For example, what does xx represent in this query? 

    GET /example/rd-lookup-gp?res=xx

I couldn't find text to explain. Is it expected to be the address of a resource, like href or anchor+href ?

**Comment by petervanderstok** [comment]
Hi Michael,

 From version 04 to the current version the ?res has undergone a change
In the -10 example the return is 
<coap://[FDFD::123]:61616/res/0>;rt=sensor;ct=60
where I might have expected <coap://[FDFD::123]:61616/0>;rt=sensor;ct=60
But I cannot check because we do not know the contents of the RD

and hypothesizing now: ?res=xx
would have returned nothing unless there was an entry like
<coap://[FDFD::123]:61616/xx/0>;rt=sensor;ct=60

and even more confusing we have something called resource-param.
In an earlier e-mail Christian already suggested to modify that to 
link-param if I remember correctly.

So yes, I can concur with you and agreeing with the existence of 
confusion.

Peter

Michael Koster schreef op 2017-05-05 16:01:

**Comment by chrysn** [comment]
The last I had in mind about the parameter a short mention in the phone call -- to me it looked like a relic whose role has been superseded by ins et al. It is now the first time I perceive it as a parameter that does anything with the path.

What is the intended overall purpose of res=? And what do you mean by the contents of the RD?

**Comment by petervanderstok** [comment]
Hi Chris,

I assume this a sequel to my answer to Michael. May be not.....

> 
> What is the intended overall purpose of res=? And what do you mean by
> the contents of the RD?

The contents of the RD are all the information about ep, resources, etc. 
stored into the RD by whatever means.

My speculation about res=xx
means that it indicates filtering on resource paths which start with 
/xx/......

Peter

**Comment by chrysn** [comment]
For such filtering, there is already `href=/xx/*`, which is covered by the `resource-param` query parameter referencing RFC 6690.

@"contents of the RD": I see. Going through all the `res` references in the document, it seems to me that the `<coap://[FDFD::123]:61616/res/0>;rt=sensor;ct=60` examples you mentioned are not about the `res` lookup parameter, but just the arbitrary resource names in the pagination example.

I'd suggest removing the parameter altogether (PR #17) unless its use resurfaces.

**Comment by mjkoster** [comment]
I think "res" (for resource) may be useful as a link target attribute for tagging resources, and in that context could also be used as a lookup parameter. If we don't plan to create "res" as a target attribute we should remove it from the document. If we do want to define a new target attribute, maybe we can come up with something more descriptive than "res"...
