### ISSUE TITLE
Criterion for being in administrative interface

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#164]
Moving this from mail (why can't github link to arbitrary URLs? Original mail: <mid:20180927143411.GD26269@hephaistos.amsuess.com>) here, as the current structure seems to have caused confusion with several readers:

> > Appendix may also be section 7.
> > The criterion was the manipulation of registration resources.
> > That got a bit mixed in the group context.
> 
> I don't think that's a useful criterion from a spec user's point of view. To me it'd make more sense to split them based on its expected use, be it "EP-side and everything else" (moving all lookup to appendix) or "EP's operations and resource lookup are regular operation,
> everything else is administrative".
> 
> I have no strong feelings either way whether it's a section 7 or an appendix.

Concrete proposal (I agree that this is yet another overhaul, and am happy to have it downvoted, but at least *if* we change the structure one more time we should get it right)

* Have a section describing discovery. That would encompass -15 sections 4, 4.1, 5.2
* Have a section "The Registration Interface", from current 5.3*, A.1 and A.2 ("Everything a Registrant-EP needs to know"). I advocate deferring A.3 to "Could be specified (like iPATCH (A.4))", and those two would be footnotes of that section.
* Leave 7 (lookup interface) largely as it is
* Move Groups into the appendices (they're very disconnected from the rest, and might even have potential for splitting off, given their practical application is under discussion)
* Turn the rest of Appendix A into "Administrative lookup interfaces", describing endpoint and group lookup.

That'd mean that implementors of clients (EP as well as lookup) have a single chapter of interactions they can follow, and only implementors of CTs need to look into the appendices.

**Comment by petervanderstok** [comment]
Hi Chris,

thanks for the suggestion.
I agree about the confusion in the section headers and structure.
Doing it all over again is a lot of work and creates additional
confusion.
Is it worth it?

Anyway, any restructuring needs much more thought from my side.

Peter
chrysn schreef op 2018-10-04 18:13:

> Moving this from mail (why can't github link to arbitrary URLs? Original mail: mid:20180927143411.GD26269@hephaistos.amsuess.com) here, as the current structure seems to have caused confusion with several readers: 
> 
> Appendix may also be section 7.
> The criterion was the manipulation of registration resources.
> That got a bit mixed in the group context. 
> 
> I don't think that's a useful criterion from a spec user's point of view. To me it'd make more sense to split them based on its expected use, be it "EP-side and everything else" (moving all lookup to appendix) or "EP's operations and resource lookup are regular operation,
> everything else is administrative". 
> 
> I have no strong feelings either way whether it's a section 7 or an appendix.

Concrete proposal (I agree that this is yet another overhaul, and am
happy to have it downvoted, but at least _if_ we change the structure
one more time we should get it right) 

 	* Have a section describing discovery. That would encompass -15
sections 4, 4.1, 5.2
 	* Have a section "The Registration Interface", from current 5.3*, A.1
and A.2 ("Everything a Registrant-EP needs to know"). I advocate
deferring A.3 to "Could be specified (like iPATCH (A.4))", and those two
would be footnotes of that section.
 	* Leave 7 (lookup interface) largely as it is
 	* Move Groups into the appendices (they're very disconnected from the
rest, and might even have potential for splitting off, given their
practical application is under discussion)
 	* Turn the rest of Appendix A into "Administrative lookup interfaces",
describing endpoint and group lookup.

That'd mean that implementors of clients (EP as well as lookup) have a
single chapter of interactions they can follow, and only implementors of
CTs need to look into the appendices. 

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [1], or mute the thread
[2]. 

Links:
------
[1] https://github.com/core-wg/resource-directory/issues/164
[2]

**Comment by chrysn** [comment]
On Fri, Oct 05, 2018 at 12:42:08AM -0700, peter van der stok wrote:
> I agree about the confusion in the section headers and structure.
> Doing it all over again is a lot of work and creates additional
> confusion.
> Is it worth it?

I can't answer that. What I do think worth considering is that anything
we do now confuses only the 10 people who have read -13 to -15, while
the final version will be read by many more.

**Comment by petervanderstok** [comment]
MOving group out of the management into a separate section and making group lookup part of resource lookup, I think the need for restructuring has gone

**Comment by chrysn** [comment]
> well it is about group registration..... 

Yes, but unless we want to split out the last paragraph, it's also about lookup. Being a 5.3.3 section indicates that it'd be another variation of registration (like simple or third-party) -- might make it 5.3.3.1 as it's a special form of third-party, but I think that's too deeply nested for something that is easiest understood after all the ground work of registration and lookup has been explained.

**Comment by petervanderstok** [comment]
removing the last paragraph of 5.3.3 Group Registration, reduce the text to registration only.
The group lookup text is just an example at the end of section 6, completely appropriate.

**Comment by chrysn** [comment]
I don't think it's a good idea to spread out groups, both from
specification and didactic point of view.

Once one has understood (or implemented) an RD, they can then look at
how to do groups with it, from registration to lookup in a single
section. Keeping the group registration where it is now gives the
impression that it's something conceptually different (like simple or
third party registration), while it is not.

**Comment by chrysn** [comment]
This discussion has drifted from the original point, so basically there's two questions now:
* Where should groups go?
* Does the split of registration and administrative interface make sense?

I'd rather discuss the former when the later is resolved; I'm still on https://github.com/core-wg/resource-directory/issues/164?_pjax=%23js-repo-pjax-container#issuecomment-427276779 as far as that is concerned; implementers need to jump around all through the document to even build the most Registrant-EP state machine.
