### ISSUE TITLE
In simple registration, the query of /.well-known/core should be allowed inline

### ISSUE THREAD

**Issue by jimsch** [core-wg/resource-directory#186]
When doing simple registration, I do not believe that it should be a requirement that the result MUST be returned prior to doing the query.  This allows for situations where the EP believes itself to be registered when in fact is is not because the query to /.well-known/core failed for some reason.  Additionally, the EP no longer has a cue as to when it can shut down because it does not know how long it will be before the RD performs the query operation.  If this is done inline then both of these situations are addressed.

**Comment by chrysn** [comment]
Unfortunately, prescribing the other direction is problematic for
endpoints that can't have both an outgoing request pending and process
an incoming one (eg. they might 5.03 while waiting for a response).

(Prescribing neither could end in both kinds of breakage).

I see the issue about full success state as well (though note that only
failures due to connectiviy errors when asking back and due to the
parsing of the .wk/c would trigger late; "you can't have that ep value"
could still send an error immediately); I just don't know how to satisfy
both requirements at the same time.

(Sleepy devices don't worry me that much, as I'd expect that unless
their sleep is externally managed, they'd have some timeout after their
last communication anyway, but please correct me if I'm wrong here, I
might have lost track of a sleepy-device draft that was.)

**Comment by jimsch** [comment]
I see what you are saying about that type of endpoint, but I would think that this is even more prone to other failures as it could probably only ever deal with one incoming request at a time as well.  This means that the RD is going to have to do retries of the query depending on the failure scheme.  I would really expect that this type of device would be more  CT device.

The yuck ways to satisfy it is to either claim external information or a new query parameter.  

You probably need to justify this in the document by talking about why.  If that existed I would probably not be as adamant about trying to solve this.

I don't remember anything you have missed about sleepy devices.  I don't have a good handle on them mostly I just guess.

**Comment by petervanderstok** [comment]
HI all,

The simple registration has worried me for other reasons as well.
Probably, it would be better off with CT registration, and probably most
installers would prefer this.
But, suppose, I am this small company doing automatic lights in toilets;
no CT; it is too expensive (difficult).

Consequently, We need to keep the simple registration.
Actually, I don't mind if the small device reintializes his request when
it has had no feedback from the RD.

Remains the case that small device has responded to RD and is happy, but
answer has not arrived correctly.
So, both RD and small device could do retries.
In the extreme we have small device and RD both doing retries untill
finally things arrive correctly in RD,  or into infinity. 

Some text pointing out the retry strategy is wanted? There are more
places in the RD that need similar consideations. I don't think it is
necessary, because it does not really affect interoperability.

Peter
Jim Schaad schreef op 2018-12-11 04:00:

> I see what you are saying about that type of endpoint, but I would think that this is even more prone to other failures as it could probably only ever deal with one incoming request at a time as well. This means that the RD is going to have to do retries of the query depending on the failure scheme. I would really expect that this type of device would be more CT device. 
> 
> The yuck ways to satisfy it is to either claim external information or a new query parameter. 
> 
> You probably need to justify this in the document by talking about why. If that existed I would probably not be as adamant about trying to solve this. 
> 
> I don't remember anything you have missed about sleepy devices. I don't have a good handle on them mostly I just guess. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/186#issuecomment-446055071
[2]

**Comment by chrysn** [comment]
> Actually, I don't mind if the small device reintializes his request when it has had no feedback from the RD.

That's a good point that'd help small device authors get it right. If they rather fail their request (but serve the GET), they can retry and the RD can work on a cached representation of .wk/c. Thus, we can switch to the version Jim preferred, and I had rejected before because it'd be hard on single-network-buffer devices.

Updated text coming up.

**Comment by chrysn** [comment]
Changed as suggested; does that work for you?

**Comment by jimsch** [comment]
Looks fine

**Comment by petervanderstok** [comment]
Hi Chris,

sending the POST from constrained device as a NON, seems a good
solution.
The constrained device not receiving the GET, can always reiterate the
POST.
We're talking single packet requests anyway.

Peter
chrysn schreef op 2018-12-17 12:28:

> (redirecting the discussion from the patch back to the issue thread)
> 
> On Mon, Dec 17, 2018 at 03:14:01AM -0800, peter van der stok wrote:
>> The issue is that the RD can send requests asynchronously to a
>> constrained destination while requests from that destination are still
>> outstanding. Constrained devices may possibly handle only one request at
>> the time. 
>> 
>> Consequenty, when a constrained device having sent a POST to the RD,
>> recieves a GET from the RD before the constrained device has received
>> the answer to the POST, the state in the constrained device is
>> undefined. Which leads to possibly lost data or non terminating
>> registrations.
>> 
>> Therefore, the RD MUST send the GET request 1-2 seconds after answering
>> the POST from the constrained device.
>> 
>> BTW: The mDNS follows the same strategy of delayed reactions to avoid
>> network congestion and changed message ordering,
> 
> I'd hope that having the CoAP REST protocol underneath us in the RD can
> help us do better.
> 
> The basic two wishes here seem essentially incompatible:
> 
> * The operator's desire: Getting a reliably successful response back.
> * The implementor's desire: Not exceeding a device's limited resources.
> 
> When this first came up, I picked the implementor's side. Reviewing that
> after Jim voiced his concerns, I think that we can make both happy by
> allowing transient failure from the device's PoV -- something REST is
> good at.
> 
> We can have both properties, and all it takes is for the embedded device
> to "admit to its shortcomings" and not to not try to hold on to an
> outgoing request it would retry anyway. In some implementations, this
> may mean that the registrant must send its registration request as a
> NON, but that's all there is to it.
> 
> Failure needs to be handled in the registrant anyway. Either prescribed
> behavior (answer-POST-then-GET and wait-for-GET-then-answer-POST) avoids
> non-terminating processes; undefined states should AFAICT occur in
> neither (save implementation bugs). 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/186#issuecomment-447813195
[2]

**Comment by chrysn** [comment]
I think with that we can close that issue.

(As a closing remark, I'd like to note that the registrant should never "wait for" the RD's GET, as a GET needs to be side-effect free and the endpoint can barely ever know whether the RD might have a cached repersentation of its discovery resource. The registrant only needs to be prepared to answer a GET if one arrives, and otherwise needs to accept the response to the POST. But actually that's only CoAP processing and not directly RD related.)

**Comment by petervanderstok** [comment]
agree, for me it is understood and improved.
chrysn schreef op 2018-12-17 17:35:

> I think with that we can close that issue. 
> 
> (As a closing remark, I'd like to note that the registrant should never "wait for" the RD's GET, as a GET needs to be side-effect free and the endpoint can barely ever know whether the RD might have a cached repersentation of its discovery resource. The registrant only needs to be prepared to answer a GET if one arrives, and otherwise needs to accept the response to the POST. But actually that's only CoAP processing and not directly RD related.) 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/186#issuecomment-447909828
[2]
