### ISSUE TITLE
idnits before –19

### ISSUE THREAD

**Issue by cabo** [core-wg/resource-directory#189]
In addition to the below, idnits also does not detect that the reference to I-D.arkko-core-dev-urn is outdated -- it should reference I-D.ietf-core-dev-urn (if we want to continue referencing dev-urn).

  == Unused Reference: 'I-D.arkko-core-dev-urn' is defined on line 2932, but
     no explicit reference was found in the text

  == Unused Reference: 'I-D.ietf-anima-bootstrapping-keyinfra' is defined on
     line 2954, but no explicit reference was found in the text

  == Unused Reference: 'RFC8392' is defined on line 3011, but no explicit
     reference was found in the text

**Comment by chrysn** [comment]
I'll remove dev-urn -- that got in by an example of what's unsuitable for use in a `base` as it doesn't have a path. (Leaning about URIs for CoRAL I learned that they have nothing *but* a path, and by now I even think that a dev urn can be used like any of the path-ful base URIs (which we allow but can't really use because a 6690 document can't use the paths). But I don't want to spend Prague arguing over that, which is what'd happen if I put an example of a `base=urn:dev:mac:0024befffe804ff1/` in there that registers a CoRAL `hosts <foo>` to become `urn:dev:mac:0024befffe804ff1/foo` just to justify having the reference).

keyinfra had a short appearance when discussing security aspects, but has become irrelevant with the new wording as well, as did 8392.
