### ISSUE TITLE
Semantics of the <>;x=... syntax in group and domain lookup

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#21]
RFC5988 (web linking) describes that a statement of `<B>;C=D` in the context of A means that "A has a hosted resource at B, which has the attribute C=D" (with the implied "hosts" relationship from RFC6690).

The repeated entries of the pattern `<>;d="domain-name"` currently drafted for the domain lookup interface (and the analogous group lookups) are bear no such meaning, and all provide statements about the same resource.

In a way, they could be collapsed into `<>;d="domain1";d="domain2"` (or `d="domain1 domain2"`).

Given it then talks about the currently used resource-directory (that is `<>`), isn't that a more straightforward to express the desired information anyway?

**Comment by mjkoster** [comment]
See issue #35 
I think we need to include the group resource location, which is returned when a group is created, in the angle brackets or "href".
I also believe we shod not specify a "domain" lookup because we decided to specify domain as an attribute of a registration. There is no domain table to do lookups on...
