### ISSUE TITLE
Examples: some have missing "Content-Format: x" in response; or missing "Res:" line before response.

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#315]

**Comment by chrysn** [comment]
Thanks, fixed. (I'm eliding Content-Format where it does not immediately relevant and I trust the human reader to correctly use the only format we actively use in this document).

**Comment by cabo** [comment]
On 2021-02-22, at 10:40, chrysn <notifications@github.com> wrote:
> 
> (I'm eliding Content-Format where it does not immediately relevant and I trust the human reader to correctly use the only format we actively use in this document).

Do you say so when introducing the examples?

Grüße, Carsten

**Comment by chrysn** [comment]
> > (I'm eliding Content-Format [...])
> 
> Do you say so when introducing the examples?

No, but a) neither do we claim the examples to be complete (they show no
token or ETag either) and b) we don't even require the option to be
there (especially not when the mandatory-to-support content format is
used and no Accept says otherwise).

I can add a statement if you still think it should be mentioned.
