### ISSUE TITLE
groups processing

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#35]
This is original comment by Jim, which have been restated partially by the issues before

I am going through the group processing and I have the following issues:

1.  There are no methods defined for modifying the contents of a group.
There is only a method for replacing the contents entirely.  Is this
intentional?

2.  The description of the context parameter looks to be a cut and paste
that you did not review.  If the parameter is absent, I do not believe that
it makes sense to try and infer a context.  My assumption is that a context
is only going to supplied in the event that a multicast address is
associated with the group.

3.  Similar to the request for a GET on the resource directory to get the
list of resource registries, I believe that you should have a GET on the
group directory to get the list of group registries.

**Comment by mjkoster** [comment]
It looks like some updates may have been missed in the group and group lookup sections. In addition to the points below, we should look it over carefully again. Thanks again for the careful review.

A group lookup (using the lookup resoure rd.lookup-group) returns a list of links to group resources where endpoints in the group contain resources that satisfy the match criteria. So if I specify a resource type in a group query, the result is expected to be a list of group resources where each group contains one or more endpoints that in turn contain one or more resources of the resource type specified in the query. We should specify that a group is included in the returned list of groups if any link in any endpoint in the group contains a matching target attribute e.g. "rt".

The examples of group lookups need to be corrected. The "href" value or string in angle brackets should contain the location path that was returned when the group is registered. I think we also need to clarify that registering a group with "con=" will set the multicast address for the group and will be returned on group lookups as "con=" rather than substituting the multicase address for the href location. (section 6.1) I guess the description of "con" is a copy/paste from the registration section. 

I think the statement about using an endpoint domain attribute as a group domain attribute may need to be removed. I think a group may contain endpoints with different domain attribute values.

**A similar question exists for the "res" query parameter.  For a group, does
this mean that the multicast address is being matched or a resource for some
endpoint in the group is being matched?** 

"res" is resource name, and I'm not sure exactly what that refers to elsewhere in the spec. I therefore presume it's a resource target attribute that the resource can be registered with and queried on. If so, we should provide an example.

**You need to look at each of the items and determine what it means for each
lookup resource type and identity it for the reader.**

Yes, good point. We need to enumerate more of the matrix with examples. I believe all of the cross product of query parameters and lookup types are legal and sensible, but will look it over again and provide some more examples.
