### ISSUE TITLE
multiple authorities per ep

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#36]
Jim Schaad schreef op 2017-09-06 00:14:
One of the issues that I just come up with, and might be part of an I
don't care space, is that if an endpoint has two different addresses
then the registration resource cannot have two different addresses
associated with it.  You cannot have two different registration
resources with the same endpoint name.  This means if I want to
register both IPv6 and IPv4 (or
other address types) with the same endpoint there is a problem.   I
also
just realized that same issue arises with schema.  These only apply if
you want to use the context parameter.  If you are going to supply
full URL addresses to resources then this is doable.  Given that the
context parameter is for space savings, I wonder if some method of
dealing with this should be considered.  Possibly defining some type
of context selector or something?

Jim

Indeed this is an issue that was also brought up by Dave Thaler, where he
referred to the multiple types of coap schemes that became possible.

For the moment, we made the model such that and extension to multiple
contexts is possible, but not yet supported by the RD, given that all
these
extensions are still under discussion,

Peter

One way that I have thought of dealing with this is to extend the check on
endpoint uniqueness from <domain, endpoint> to <domain, endpoint, context>.
The only downside that I can see is that it makes the query on the endpoint
resource slightly more complicated.

**Comment by chrysn** [comment]
Hello Jim,
Hello Bill and Mert,

On Fri, Sep 08, 2017 at 09:28:41AM +0200, peter van der Stok wrote:
> For the moment, we made the model such that and extension to multiple
> contexts is possible, but not yet supported by the RD, given that all these
> extensions are still under discussion,

More concretely, this is where I hope that
core-coap-protocol-negotiation will take over. We're deliberately
keeping multiple-base-addresses out of resource-directory (an earlier
state already allowed more than one address) so this can be
comprehensively specified there based on model that contains only the
extension point for it.

Bill and Mert, Jim the issue Jim raised is not fully covered by the
protocol-negotiation draft or what we talked about in Prague, but
involves the choice of an Internet layer when raw addresses are used.
Will we be able to use the mechanisms introduced there in the absence of
hostnames for an IPv4 and an IPv6 addresses (or multiple IPv6
addresses)?

Best regards
Christian

-- 
This may seem a bit weird, but that's okay, because it is weird.
  -- perldata(1) about perl variables

**Comment by chrysn** [comment]
This is now covered in appendix B -- that won't stay for the final document, but won't need to because of protocol-negotiation.

**Comment by chrysn** [comment]
Hi Christian,

The issue Jim raised was not covered with protocol-negotiation draft indeed in the version we discussed in Prague. That version proposed a way to expose alternative transports on a per-server basis. However, in the new version of the draft for Singapore, we are introducing a new link attribute "ol" : other locations, in which the CoAP server can expose the same resource on different locations/transports. The new attribute works as a per resource basis and can be used both on RD or on /.well-known/core. This way enables exposing resources both per-server or per-resource on the same server, something we had several discussions about in Prague. The new attribute also prevents overloading the meaning of "con", since the original idea of "con" was not intended for per-resource.

This approach can be used for exposing the same resource on different raw addresses as in the Jim's issue since we are not restricting the use of "ol" for just different transports. 

Cheers,
Mert


On 21/09/2017, 15.01, "Christian Amsüss" <chrysn@fsfe.org> wrote:

    Hello Jim,
    Hello Bill and Mert,
    
    On Fri, Sep 08, 2017 at 09:28:41AM +0200, peter van der Stok wrote:
    > For the moment, we made the model such that and extension to multiple
    > contexts is possible, but not yet supported by the RD, given that all these
    > extensions are still under discussion,
    
    More concretely, this is where I hope that
    core-coap-protocol-negotiation will take over. We're deliberately
    keeping multiple-base-addresses out of resource-directory (an earlier
    state already allowed more than one address) so this can be
    comprehensively specified there based on model that contains only the
    extension point for it.
    
    Bill and Mert, Jim the issue Jim raised is not fully covered by the
    protocol-negotiation draft or what we talked about in Prague, but
    involves the choice of an Internet layer when raw addresses are used.
    Will we be able to use the mechanisms introduced there in the absence of
    hostnames for an IPv4 and an IPv6 addresses (or multiple IPv6
    addresses)?
    
    Best regards
    Christian
    
    -- 
    This may seem a bit weird, but that's okay, because it is weird.
      -- perldata(1) about perl variables

**Comment by chrysn** [comment]
<del>
Hello
I have a business partnership proposal for you. Contact me on my
personal email for more details please :
***@***.***


Regards
Saif
</del>

[edit: My guess is that this spam item came about by me group replying between a mail from GitHub and an IETF list thread; the latter was crawled by a bot that started sending to the reply address which got this in here b/c GitHub uses their reply EMail addresses like bearer tokens which neither expire nor can be revoked. Sorry for my part in this, let's see whether GitHub enhance their security on this.]

**Comment by chrysn** [comment]
See edit on what has happened here.

Locking the conversation because apparently there is no mitigation for GitHub's bearer tokens in EMail addresses, let's hope the locking also affects mails from me.
