### ISSUE TITLE
PATCH

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#39]
So, with this new understanding I am going to try some different questions
about PATCH.

1.  Is there a good reason to support the addition of new resources in two
different methods?  Addition of new resources can already be done through
the POST method, needing to recognize that the documents to be patched are
different is a potential error waiting to happen if this is not well
described in document.

2.  For the delete case, the patch string of {"href":null}  is more in line
with how I understand a JSON patch document to be designed.  The string of
{} would say that nothing is to be changed by default unless it is special
cased.  Setting the value of the href to absent or null would be easily
understood as saying remove the element.

3.  The text on patch needs to be clear on how to treat a patch document
where multiple occurrences of an attribute to modify occur in the patch
document.  It should also be clearer on the correct way to deal with
updating multiple occurrences of the attribute in the link document.  My
reading of the current text could end up with "</foo>;alpha=beta;alpha=beta"
as the output if the input was "</foo>;alpha=gamma;alpha=delta" and the
patch was {alpha:"beta"}.   I am not sure that is what you want to be
saying.

4.  This paragraph is missing some text I believe:

If the PATCH payload results in the modification of link target,
   context, or relation values, that is "href", "rel", or "anchor", the
   request SHOULD be rejected with a "Conflict" result code.

Why is this a SHOULD and not a MUST.  If you keep it as a MUST some guidance
on which rejections SHOULD occur and when they are acceptable would be
highly desirable.  Making it a MUST means that a Conflict response would not
be able to occur if I have my logic correct for anything other than an
addition request.

**Comment by petervanderstok** [comment]
Hi Michael,

The use of /application/merge-patch+json in the section update links is not correct.
The media type allows to update individual JSON objects but replaces complete arrays.
i.e. In your example the two links are replaced by one link.

In your example with

original contents
</sensors/temp>;ct=41;rt="temperature",
</sensors/light>;ct=41;rt="light-lux";if="sensor"

and then executing

Req: PATCH /rd/4521

Payload:
[{"href":"/sensors/humid","ct": 41, "rt": "humid-s", "if": "sensor"}]

Content-Format:
application/merge-patch+json

Res: 2.04 Changed

Req: GET /rd/4521

Res: 2.01 Content
Payload:
</sensors/humid>;ct=41;rt="humid-s";if="sensor"

Also removing the square bracket [..] "may lead" to adding a single objects next to and outside the array

I am afraid you have to define a new media type and specify the rules for replacing single array items (links).

For example there is an ambiguity for the following Patch

Req: PATCH /rd/4521

Payload:
[{"href":"/sensors/light","ct": 41, "rt": "light-lux", "if": "light-sensor"}]
Content-Format:
application/merge-patch+rd

Res: 2.04 Changed

Req: GET /rd/4521

Res: 2.01 Content
Payload:
</sensors/temp>;ct=41;rt="temperature",
</sensors/light>;ct=41;rt="light-lux";if="light-sensor"

OR may result in:

</sensors/temp>;ct=41;rt="temperature",
</sensors/light>;ct=41;rt="light-lux";if="sensor"
</sensors/light>;ct=41;rt="light-lux";if="light-sensor"

These ambiguities are to be looked after in the new patch text and media format.

Another solution: remove the patch text in the next version of RD.

Greetings,

Peter

**Comment by mjkoster** [comment]
The design in this draft for patching link arrays uses query functionality to select one or more elements of the array, then applies the merge-patch payload to each selected element as a separate patch. I think the working of the design is often misunderstood and needs to be made more clear in the explanation and examples.

This design seems to make sense for the use case of a client patching links, because the client already uses query parameter matching to select the links of interest, then can perform a patch operation on the relations and attributes of the link.

It could be that the syntax of the patch payload should be a map rather than an array...

**Comment by mjkoster** [comment]
**Is there a good reason to support the addition of new resources in two
different methods?**

There is a good reason to allow links to be modified, and if that functionality inadvertently allows obvious syntax for adding links, IMO there is good reason that it should not be prohibited, even if it results in two way to add things. Being a hypermedia system, this should not break anything

**Setting the value of the href to absent or null would be easily understood as saying remove the element.**

IMO, "null" is not good practice, and an empty "href" is legal in a link. By comparison, empty JSONs are quite common.

**...the current text could end up with ";alpha=beta;alpha=beta"
as the output if the input was ";alpha=gamma;alpha=delta" and the
patch was {alpha:"beta"}**

I don't see the issue with json merge patch here as long as we think of the target document in application/link-format+json format.
Looks to me like the file has {"alpha": ["gamma", "delta"] } to start with so the patch needs to include a new (string or array) value for alpha. Your example patch results in {"alpha": "beta"}. Am I missing something?

**If the PATCH payload results in the modification of link target, context, or relation values, that is "href", "rel", or "anchor", the request SHOULD be rejected with a "Conflict" result code.**

Should we be able to change the target address of a link? Interesting question. I think there may be a use case in moving a device, but it could be argued that the device should re-register.

Since a link allows multiple relation values (as a compact representation) I think there is a good case for adding or removing relation values.

**Comment by chrysn** [comment]
Patch was deferred to whatever defines a suitable patch format.
