### ISSUE TITLE
read endpoint links.

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#77]
I don't see any reason to keep this section as pointed out during the last telco.
When it is removed some examples i Registration update must be changed.

The request
GET /rd/4521

should change to
GET /rd-lookup/ep?href=rd/4521

**Comment by petervanderstok** [comment]
Apologies, that will not return the links of the endpoint
The request
GET /rd/4521

should change to 
GET /rd-lookup/res?ep=/rd/4521

or
GET /rd-lookup/res?ep=node1

I am afraid we need to stay with ep name, difficult to use /rd/4521 as ep identifier.

**Comment by chrysn** [comment]
The equivalent requests would be

    GET /rd-lookup/res?ep=node1

and

    GET /rd-lookup/res?href=/rd/4521

(where the link has neither the ep=node1 nor the href=/rd/4521 link parameter, but its registration does).

**Comment by chrysn** [comment]
I think that we don't need the GET as long as there are no PATCHes (and I recently saw we don't even define PUT for the registration resource).

The discussion has shown that this is one of the points where our understanding of resolved and unresolved addresses is tested: Can we have a resource whose content is "unresolved link-format" to operate on? Or do we need to resolve the links even in there, and any PATCH format would need to work semantically from a shared understanding of both the RD and the client?

@cabo, you wanted to meditate on that; have you found deeper truth, or a path there?

**Comment by petervanderstok** [comment]
This weird indeed:

> GET /rd-lookup/res?ep=node1

In my understanding this means return all link resource paths with ep 
name node1

and
GET /rd-lookup/res?href=skins/larry/rd/4521

means return all link resource paths with href is skins/larry/rd/4521
and will be empty


chrysn schreef op 2017-10-30 13:03:

**Comment by chrysn** [comment]
`/res?href=skins/larry/rd/4521` returns resources that either have `skins/larry/rd/4521` as their own link href, or are contained in an endpoint or group with that href.

This was introduced in #68 because we do not have (due to the extensibility of the link attributes and the lack of a definitive registry) a partition on attribute names that clearly states that one attribute can only be on a group, another only on an endpoint and a third only on a resource. Thus, we need to expect matches from either level -- and once we already have to do this, we can just as well do it with href because it's treated like any other attribute.

IMO the alternatives to this would be either having registries set up to partition the names so every query parameter is clearly an endpoint, group or resource attribute (probably not going to happen with resource attributes, as requested and denied in RFC5988bis), or we'd need a more complex lookup language than RFC6690-style search -- something like `/res?<endpoint>et=power-node` so we could be explicit there.

(See also https://github.com/core-wg/resource-directory/issues/82 )

**Comment by petervanderstok** [comment]
Ok, you go faster than my shadow.
As long as the text covers the example, and the intention is clear.
I will need to read the finished text again.



chrysn schreef op 2017-10-30 16:29:

**Comment by chrysn** [comment]
(Moving some comments here from EMail to keep track:)

[Peter] I thought we agreed to remove section 5.4.3,

[Christian] I had that taken down as "we should think about it some more"; I do expect that interfact to only become useful when we have a way to patch it.

**Comment by petervanderstok** [comment]
Given the current direction of lookup with construction of absolute URI, we can leave section 5.4.3 in
