### ISSUE TITLE
Type representation

### ISSUE THREAD

**Issue by onovo1** [core-wg/resource-directory#92]
The Resource Directory uses some query parameters or link attributes to represent the types of the endpoints and resources. For instance, rt (resource type) or ep (endpoint type). 
However, the representation of the types is not defined in the Resource Directory document and it seems that the different endpoints can represent the different type values as they wish. 

Not having an standardized representation of the different types can lead to undesirable outcomes. For instance,  let's assume that a humidity sensor registers itself as a "humidity" resource type.  Now, there is another endpoint that has been manufacture in a Spanish speaking country and performs a resource lookup of all the humidity resource types but it looks for "humedad" instead. "Humedad" is the Spanish word for "humidity":  
  ` Req: GET /rd-lookup/res?rt=humedad`

In this particular case, the Resource Directory will not be able to match the search with the humidity sensor and the search will not appear in the lookup results.

I know that is very difficult to match all the possible endpoint types but it would be good to define what is allow and what is not as a value of a type. Shall do always be expressed in English? Shall do always be a name or verb?

**Comment by chrysn** [comment]
Both endpoint types (et=) and resource types (rt=) need to be registered
values (or URIs, but I won't comment on them further in this issue
unless you ask), but at any rate are only matched lists of strings.

These are not free-form fields, and not necessarily meaingful (English)
words. For example, for rt, currently registered values are 'core.hc'
(HTTP-CoAP proxy resources) or 'oic.*' or 'oma.lwm2m' from other
standardization organizations.

We are using examples like et=wallmounted here because nobody has yet
inserted more concrete values into that registry, but don't expect that
actual use will look exactly like that.


To get this forward as an issue, we could
* [ ] come up with more meaningful examples
* [ ] mention that the RD does not try to normalize those values or
  otherwise make any effort to match types that don't literally match

Thanks for your input
Christian

**Comment by petervanderstok** [comment]
* [ ] mention that "humidity" is an example "et=" value used throughout 
the document and the document does not try to normalize "et=" values

or another preferred example value.

**Comment by onovo1** [comment]
Thanks for your comments. 

At least, I know that other standardization organizations have already standardized similar values. For instance, IPSO Smart Objects already defined the semantic type of many objects in unsigned 16-bit integers called 'Object ID'. Wouldn't make more sense to use and refer to those values in the RD document?

**Comment by petervanderstok** [comment]
changed text and used et="oic.r.humidity"; also mentioned that this is a registered value for et=

**Comment by onovo1** [comment]
Yes, that could be an option, using the definition of the "OCF Resource Model" in this particular case. 

The RD document does not use the Endpoint type "humidity" in the document but there are others endpoint and resource types defined which do not have a proper registration such as: power-node, sensor-node, light, p-server, temperature, sensors, light-lux or temperature-c.

**Comment by petervanderstok** [comment]
will try to catch the others as well

**Comment by petervanderstok** [comment]
what about registering example values?
like ex.sensor, ex.humidity, ex.temperature, ex.power, ex.light

**Comment by onovo1** [comment]
That could be another option as long as the document state clearly that the et= and et= values should be used normalized

**Comment by petervanderstok** [comment]
Text has been adapted by using already specified values.
